### ISSUE TITLE
SNOW-1676298: Expose the possibility to disable logging completely (for .NET Native AOT)

### ISSUE THREAD

**Issue by pjmvp** [snowflakedb/snowflake-connector-net#1028] opened 2024-09-21 15:10 UTC
As of today, [the constructor for SnowflakeDbConnection calls a SFLoggerFactory.GetLogger() method](https://github.com/snowflakedb/snowflake-connector-net/blob/aef4d3af3f445b3fab411dc77bf8ef6486e2a6d0/Snowflake.Data/Client/SnowflakeDbConnection.cs#L19) which in turn [calls a GetLogger() method in a LogManager class from the log4net dependency](https://github.com/snowflakedb/snowflake-connector-net/blob/aef4d3af3f445b3fab411dc77bf8ef6486e2a6d0/Snowflake.Data/Logger/SFLoggerFactory.cs#L47).

That log4net method calls `Assembly.GetCallingAssembly()` which is not **supported when running in native AOT**.

I see that `SFLoggerFactory` has `enableLogger` and `disableLogger` methods. However, SFLoggerFactory is a private class so we cannot invoke them. I see no other way of telling the package to use SFLoggerEmptyImpl.

Ideally, the driver would use the ILogger interface, instead of log4net, and I see others have requested that as well. 
But besides that, I think that. at the very least, the package should allow us to not use any logging if we so desire. Even if one tries to do so via configuration, the SnowflakeDbConnection will always call GetLogger(). In my case, this makes it impractical (*) to use .NET Native AOT.

(*) The only way I can achieve that is with a reflection dirty-hack, using reflection methods supported in native AOT, to invoke the private method.

**Comment by pjmvp** [comment] 2024-09-21 15:10
Ref to. https://github.com/snowflakedb/snowflake-connector-net/issues/47

**Comment by sfc-gh-dszmolka** [comment] 2024-09-23 10:52
hi and thank you for raising this - indeed many of our users already require that the logging dependency is decoupled and let everyone to implement their own. This work is tracked on https://github.com/snowflakedb/snowflake-connector-net/issues/204, and as of such, I believe this (#1028) is a duplicate of the older feature request which is ought to get rid of the current logging dependency. I also believe efforts should be focused on that.

Being said that, since having the capability of a decoupled logging library seems important to you, please reach out to your Snowflake account team to let them know of this requirement. This helps prioritizing amongst the multiple requests - thank you in advance for your assistance on the matter !

Closing this one as a duplicate but if the requirement is misunderstood and delegating logging to the library consumers would not help your use case (then deciding whether and how you want to log at all), do comment please and I can reopen.

**Closed by sfc-gh-dszmolka** 2024-09-23 10:52 UTC
Labels: feature, status-triage_done
