### ISSUE TITLE
SNOW-1524454: Too many dependencies in Snowflake.Data nuget package

### ISSUE THREAD

**Issue by AndreyTomilinXmpi** [snowflakedb/snowflake-connector-net#991] opened 2024-07-08 15:34 UTC
These are current package dependencies:

> [Apache.Arrow](https://www.nuget.org/packages/Apache.Arrow/) (>= 14.0.2)
> [AWSSDK.S3](https://www.nuget.org/packages/AWSSDK.S3/) (>= 3.7.0.4)
> [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs/) (>= 12.13.0)
> [Azure.Storage.Common](https://www.nuget.org/packages/Azure.Storage.Common/) (>= 12.12.0)
> [BouncyCastle.Cryptography](https://www.nuget.org/packages/BouncyCastle.Cryptography/) (>= 2.2.1)
> [Google.Cloud.Storage.V1](https://www.nuget.org/packages/Google.Cloud.Storage.V1/) (>= 4.6.0)
> [log4net](https://www.nuget.org/packages/log4net/) (>= 2.0.12)
> [Mono.Unix](https://www.nuget.org/packages/Mono.Unix/) (>= 7.1.0-final.1.21458.1)
> [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/) (>= 13.0.3)
> [System.IdentityModel.Tokens.Jwt](https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/) (>= 6.34.0)
> [System.Text.RegularExpressions](https://www.nuget.org/packages/System.Text.RegularExpressions/) (>= 4.3.1)

My problem is that I'm are using Amazon and I don't need all other providers (libraries). It becomes complex to update all these packages and produces package version conflicts.

Why not create multiple Snowflake libraries so that each of them will support a specific cloud provider.
Say, Amazon library is divided into multiple libraries. Each of them is intended for a specific service.
For example:
> Snowflake.Data.Azure
> Snowflake.Data.Google
> Snowflake.Data.Amazon

Also, would be great if you would use built in JSON and Logging libraries instead of using third party ones.

**Comment by sfc-gh-dszmolka** [comment] 2024-07-09 04:38
hi, closing this as a duplicate of
* https://github.com/snowflakedb/snowflake-connector-net/issues/204
* https://github.com/snowflakedb/snowflake-connector-net/issues/612
we're aware of this requirement.

but if something is not tracked on the aforementioned tickets, do comment please

**Closed by sfc-gh-dszmolka** 2024-07-09 04:38 UTC
Labels: duplicate, status-triage_done
