### ISSUE TITLE
Request time out error when pulling the millions of records from the table

### ISSUE THREAD

**Issue by CPavanKishore** [snowflakedb/snowflake-connector-net#40] opened 2018-05-31 05:37 UTC
Actually while i'm trying to pull  millions of records from the table, It is throwing an exception at different points, Sometimes the code will break at after pulling 4 lakh records & sometimes at 8 lakh 

Below is the log file for the above issue
[app.log](https://github.com/snowflakedb/snowflake-connector-net/files/2056807/app.log)

**Comment by bitshop** [comment] 2019-03-29 20:07
We ran into this problem also, this is a pretty major blocker as you have to write extensive error handling and retry logic to pull large data sets from Snowflake.

**Comment by samanis** [comment] 2021-02-05 17:13
I'm having same issue. Any update ?

**Comment by sfc-gh-dszmolka** [comment] 2023-09-12 09:35
I'm closing this issue as there's been multiple driver releases since its original creation, amongst which quite severe bugs were fixed. 

If you're still having this issue with the latest 2.1.1 driver version, please comment with the driver logs and if the issue is tied to a specific scenario, then the reproduction steps too. Thank you in advance !

**Closed by sfc-gh-dszmolka** 2023-09-12 09:35 UTC
Labels: bug, triage
