### ISSUE TITLE
Enable/Disable Logging

### ISSUE THREAD

**Issue by gogowater** [snowflakedb/snowflake-connector-net#47] opened 2018-06-26 19:03 UTC
The snowflake logging produces too much noise in our log, can we add a appSetting or static property to turn on and off the logging via configuration or code?  Thank you.

**Comment by manigandham** [comment] 2018-06-26 19:35
This would also be a good opportunity to use LibLog so that logging can transparently use the framework used by the rest of the application (and its configuration) instead of being hardcoded to log4net:

https://github.com/damianh/LibLog

**Comment by howryu** [comment] 2018-06-26 21:08
@gogowater Yes I should provide a way for users to disable logs .

@manigandham Thanks for your advice. I need to evaluate different options. I tried to use some logging facade (like slf4j for java), but the problem is that we need to support both .net framework and .net core.

**Comment by gogowater** [comment] 2018-06-26 23:09
Thank you

**Comment by howryu** [comment] 2018-07-17 19:03
@gogowater It seems that log4net has a way to disable logging comes from certain namespace. I checked the stackoverflow and found this. https://stackoverflow.com/questions/5504148/log4net-configure-to-ignore-messages-from-a-specific-class 
Let me know if this worked for you.

**Comment by gogowater** [comment] 2018-07-26 16:22
@howryu Yes, that is how we filter out the log by snowflake namespace.  But we are hoping this can be set programmatically or a master config key without adding specific filter to all the appenders.  If this is too much trouble, I can understand.  Thanks again.

**Comment by howryu** [comment] 2018-08-31 16:18
For now I will close this one since I deicide not to implement it for now because filter on namespace should be good for now.

**Closed by howryu** 2018-08-31 16:18 UTC

**Comment by SnareHanger** [comment] 2020-04-27 21:44
Is there any chance this might be in the future?  My project uses a different logging framework and to have to install log4net only to disable it in a config doesn't seem a great implementation.

**Comment by dfaen** [comment] 2022-01-05 09:40
Push in 2022, can we please remove log4net due to their latest issues or at least, add a capability to set an own logger handler instead of using the SFLogger wrapper in Snowflake.Data.Client?

**Comment by MarcosMeli** [comment] 2022-09-21 22:54
It will be important to create a .net core version using the standard .net core ILogger so it will be very easy to configure and no external library is needed
