### ISSUE TITLE
Allow injecting custom logger

### ISSUE THREAD

**Issue by AdityaSantoso** [snowflakedb/snowflake-connector-net#422] opened 2022-02-21 01:57 UTC
### Issue description
In a typical .NET application, the logger are injected via ILogger<> interface. This allows us to use other logging framework such as Serilog if needed be. Currently, the logging implementation in `SFLoggerFactory` instantiates the Log4Net implementation in-line as static singleton.

```
    public static SFLogger GetLogger<T>()
    {
      if (!SFLoggerFactory.isLoggerEnabled)
        return (SFLogger) new SFLoggerEmptyImpl();
      return SFLoggerFactory.logger == null ? (SFLogger) new Log4NetImpl(LogManager.GetLogger(typeof (T))) : SFLoggerFactory.logger;
    }
```

### Configuration
*Driver version:* 2.0.8

*Dotnet framework and version:* .NET 6

### Expectation
Allow injecting custom implementation of SFLogger independent from Log4Net so it can play nicely with logging framework that is configured in the rest of the application

**Comment by xhua026** [comment] 2023-02-14 02:25
hey guys, any updates on this topic?

**Comment by sfc-gh-dszmolka** [comment] 2023-06-07 12:43
looks to be duplicate of #204

**Closed by sfc-gh-dszmolka** 2023-06-07 12:43 UTC
Labels: feature, triage
