### ISSUE TITLE
HOST is required even though it said its optional.

### ISSUE THREAD

**Issue by eddychansnowflake** [snowflakedb/snowflake-connector-net#43] opened 2018-06-20 16:30 UTC
The docs seems to be wrong, HOST is required, doesn't default if its left out of the connection string.

**Comment by howryu** [comment] 2018-06-20 22:30
I think this might be same root cause as #41. I will fix it tomorrow.

**Comment by howryu** [comment] 2018-06-21 18:05
Fixed in #44

**Closed by howryu** 2018-06-21 18:05 UTC
