### ISSUE TITLE
UseProxy property in the connection string can be misleading

### ISSUE THREAD

**Issue by pucefti** [snowflakedb/snowflake-connector-net#653] opened 2023-05-12 09:32 UTC
When you create the HttpClientHandler in HttpUtil, you don't set the UseProxy property and leave it to default, but by default the value is true.
It's obviously not a problem when we want to set a proxy or if your system hasn't a proxy configured, but when your system has a proxy configured by default and you don't want to use it, you have no way to do it because no matter if you specify in the connection string UseProxy to false or not, the proxy will still be used.

So I think that the value of the connection string's UseProxy should match the value of the HttpClientHandler, in order to be able to disable the proxy.

1. What version of .NET driver are you using?
2.0.23
   
2. What operating system and processor architecture are you using?
Windows server 2019
   
3. What version of .NET framework are you using?
.NET 6
   
4. What did you do?
In the connection string set UseProxy to false

5. What did you expect to see?
The connection is perform without using the proxy

6. Can you set logging to DEBUG and collect the logs?
Not relevant

**Comment by sfc-gh-igarish** [comment] 2023-06-23 23:04
I cannot reproduce the issue, I need more info from the reporter.
What I would ask about:

If you create a new session with a connection string, you can specify "useProxy=true" or "useProxy=false" and it works as expected. The default value for useProxy is false.

What are the exact steps to reproduce the issue?
How exactly do you create and configure HttpUtil object?
Do you create SFSession object by passing in the connection string useProxy parameter?

**Comment by pucefti** [comment] 2023-06-26 12:22
Hello,

Let me clarify, the problem is not in the UseProxy of the connection string which works as intended, but the way HttpClientHandler is build in HttpUtil.
For exemple:
I use this connectionstring:
account=test1;user=testuser;password=123;db=TEST_DB;useProxy=false;

With this one HttpClientHandler in HttpUtil will be construct as:
httpHandler = new HttpClientHandler()
{
	// Verify no certificates have been revoked
	CheckCertificateRevocationList = config.CrlCheckEnabled,
	// Enforce tls v1.2
	SslProtocols = SslProtocols.Tls12,
	AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate,
	UseCookies = false // Disable cookies
};

So with no proxy. But by default HttpClientHandler has his internal value UseProxy to true and so if a default proxy is configured in the system, it will use it even if you have specified in the connection string UseProxy=false, because this value is not passed to HttpClientHandler.

So, I think that the correct way to do it, is to add something like:
httpHandler = new HttpClientHandler()
{
	// Verify no certificates have been revoked
	CheckCertificateRevocationList = config.CrlCheckEnabled,
	// Enforce tls v1.2
	SslProtocols = SslProtocols.Tls12,
	AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate,
	UseCookies = false // Disable cookies
	**UseProxy = config.UseProxy //Align the value to the connectionstring one.**
};

**Comment by sfc-gh-dszmolka** [comment] 2023-07-03 08:29
this is fixed by https://github.com/snowflakedb/snowflake-connector-net/pull/689 and will be part of the next driver release

**Comment by sfc-gh-dszmolka** [comment] 2023-07-27 19:02
PR is released as part of the latest Snowflake .NET driver version 2.1.0. Closing this issue.

**Closed by sfc-gh-dszmolka** 2023-07-27 19:02 UTC
Labels: bug, Fixed - Awaiting Release
