### ISSUE TITLE
Error: Session no longer exists.  New login required to access the service.

### ISSUE THREAD

**Issue by mbcrawfo** [snowflakedb/snowflake-connector-net#577] opened 2023-01-05 16:00 UTC
Based on discussion in #522 it looks like this should have been fixed by #525 released in 2.0.17.  However I'm still seeing the error in 2.0.19.

Context:
I've been doing some POC work around building a GraphQL API that will use some of our Snowflake data.  I encountered the error when running locally.  The app had been running ~30 minutes and I was intermittent api calls during that time.  Every time the app needs to query Snowflake I create a new `SnowflakeDbConnection` and dispose of it immediately after the query completes.  The connection string options used are `ACCOUNT=xxx;DB=xxx;SCHEMA=xxx;USER=xxx;PASSWORD=xxx`.

Snowflake.Data v2.0.19
.Net 7 (SDK v7.0.101)
Windows 10
Snowflake Server v6.41.2

**Comment by Gonyoda** [comment] 2023-02-17 19:57
I noticed this as well - and I was able to reproduce this error fairly quickly - within 9-10 new/dispose cycles.  I found that if I turned off Connection Pooling the error went away.   So I suspect the bug is in connection pooling, but I didn't have time to research.

My fix:
```
SnowflakeDbConnectionPool.SetPooling(false);
```

**Comment by chong007** [comment] 2023-02-22 03:23
I'm also still seeing this error with `v2.0.20` with the query intermittently failing.
Turning off the connection pooling works but not ideal.

```
Snowflake.Data.Client.SnowflakeDbException: Error: Session no longer exists.  New login required to access the service. SqlState: , VendorCode: 390111, QueryId: 
  ?, in SFBaseResultSet SFStatement.BuildResultSet(QueryExecResponse response, CancellationToken cancellationToken)
  ?, in async Task<SFBaseResultSet> SFStatement.ExecuteAsync(int timeout, string sql, Dictionary<string, BindingDTO> bindings, bool describeOnly, CancellationToken cancellationToken)
  ?, in async Task<DbDataReader> SnowflakeDbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
```

**Comment by JediMasterSam** [comment] 2023-03-06 18:22
I did some investigating into this problem using [ `v2.0.21`](https://github.com/snowflakedb/snowflake-connector-net/tree/v2.0.21) and located the issue, but I have not been able to find the root cause.

In the class `SFStatement`, there is a method `ExecuteAsync(int, string, Dictionary<string, BindingDTO>, bool, CancellationToken)` and in that method there is a while-loop:

```
while (!receivedFirstQueryResponse)
{
     response = await _restRequester.PostAsync<QueryExecResponse>(queryRequest, cancellationToken).ConfigureAwait(false);
     if (SessionExpired(response))
     {
          await SfSession.renewSessionAsync(cancellationToken).ConfigureAwait(false);
          queryRequest.authorizationToken = string.Format(SF_AUTHORIZATION_SNOWFLAKE_FMT, SfSession.sessionToken);
     }
     else
     {
          receivedFirstQueryResponse = true;
     }
}
```

and the problem is occurring with the `PostAsync<>` method.  I tried adding logic to allow it to retry if it was unsuccessful, but that did not solve the issue.  It did however illuminate something quite interesting; within my code when pooling is enabled, the first 37 requests will get a valid response, but after that, they will all fail.  I was able to reproduce this over hundreds of iterations, which leads me to believe that it is not an issue with concurrency.  Also, clearing or disabling pooling after the first 37 requests had not effect, it still continued to fail just like if it had been.

Disabling pooling before any request is received does fix this issue as stated before, but when I benchmarked the performance between with and without pooling, without pooling definitely slower within the domain I am working in, so that is not an option for me.

I would be curious to know if the 37 successful responses is repeatable in anyone else's environment, or if that is specific to the configuration I am using.

**Comment by Gonyoda** [comment] 2023-03-06 20:16
It happens to me on the 10th query.  So the query succeeds 9 times and the 10th I get the error.  From that point on, the connection is broken and I have to restart the program to fix it.

For the record, what I did to enable pooling was create a class that wraps the SnowflakeDbConnection and overrides the Dispose/Close calls.

```csharp

    private sealed class MySnowflakeDbConnection : ISnowflakeConnection
    {
        private bool _shouldDispose;

        public MySnowflakeDbConnection(SnowflakeDbConnection dbConnection)
        {
            this.DbConnection = dbConnection;
        }

        public SnowflakeDbConnection DbConnection { get; }

        public Task CloseAsync(CancellationToken cancellationToken)
        {
            if (PlaceInPool(this))
            {
                return Task.CompletedTask;
            }

            this._shouldDispose = true;
            return this.DbConnection.CloseAsync(cancellationToken);
        }

        public ValueTask DisposeAsync()
        {
            return this._shouldDispose
                ? this.DbConnection.DisposeAsync()
                : ValueTask.CompletedTask;
        }
    }

**Comment by JediMasterSam** [comment] 2023-05-01 13:36
I have updated to 2.0.23 and this problem seems to be resolved. While this issue/bug are still open, I think the work has been completed.

> There are other bug fixes as well:
CLIENT_SESSION_KEEP_ALIVE in connection string. It's actually not
working as the driver didn't send it to server as session parameter
pooling timeout was reset each time when the connection is reused and
pooled again. This could make the connection never expire and
application could get error when the session expired. Set pooling
timeout only at the first time it's pooled.

Source: https://github.com/snowflakedb/snowflake-connector-net/commit/77eff379a7e3dd72ff2f2baaf365d69d27e83458

**Comment by pieperu** [comment] 2023-05-05 11:51
I can confirm also that upgrading to `2.0.23` fixed the issues for me too.

**Comment by Gonyoda** [comment] 2023-05-08 13:52
Confirmed fixed for me as well. I was able to remove my [ridiculous ConcurrentDictionary pool wrapper code](https://github.com/snowflakedb/snowflake-connector-net/issues/577#issuecomment-1456908798)... thanks!

**Comment by sfc-gh-igarish** [comment] 2023-05-26 21:40
Thanks you guys for your patience. We fix some issues related to connection pool recently. If it's working, I am closing this ticket. If you face the issue, feel free to reopen or file a new ticket.

**Closed by sfc-gh-igarish** 2023-05-26 21:40 UTC
Labels: bug
