### ISSUE TITLE
SQL compilation error: Unsupported data type 'java.util.LinkedHashMap'

### ISSUE THREAD

**Issue by danieltaiber** [snowflakedb/snowflake-connector-net#675] opened 2023-06-08 04:13 UTC
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of .NET driver are you using?
2.0.24
   
2. What operating system and processor architecture are you using?
MAC Ventura 13.4 M2 
   
3. What version of .NET framework are you using?
   E.g. .net framework 4.5.2 or .net standard 2.0
.NET 6.0

4. What did you do?
I'm trying to bulk insert using command parameters bind to arrays.
My table has 3 columns:
- REAL
- TEXT
- NUMBER(38,0)

They are inserted using the following array types:
- Double
- String
- Int32

5. What did you expect to see?
Data being inserted to table

6. Can you set logging to DEBUG and collect the logs?

7. What is your Snowflake account identifier, if any? (Optional)
https://zkejjta-kb00154.snowflakecomputing.com

**Comment by sfc-gh-dszmolka** [comment] 2023-06-13 06:14
hello and thank you for raising this issue. can you please provide a minimal viable reproduction snippet, which when run, displays the behaviour you raised the issue for ? 

also if your situation requires Snowflake-side preparation (e.g. setup a table) or has other, data-specific aspects,  please share that as well. 

this would immensely help us debugging your issue. thank you in advance !

**Comment by sfc-gh-dszmolka** [comment] 2023-06-14 14:52
sounds great ! just for the sake of people who might hit the same in the future, if you wish, you could comment what the solution for you was. might help others too. 

but, since the issue is resolved for you, i'm marking this as closed (you can still comment on a closed case :) )

**Comment by danieltaiber** [comment] 2023-06-15 06:43
Wow,

You won’t believe it.
Actually there is a point for you guys to fix I think.

I had a problem where I would fire a bulk insert using array binding and it would fail. When I tried reproducing it in a side application it succeeded.

After tons of debugging, I found out that when you guys fire the HTTP POST request to run the query, you add the arrays and binding parameter.
But you serialize it using Newtonsoft JSON serializer, and you use the JSON defaults from JSONUtils.

But…
You set the contract resolver to default and forget about other properties.
We are using
TypeNameHandling = TypeNameHandling.Auto
In our application, which causes your arrays to serialize in a format that your backend fails to deserialize.

I think you should set all JSON options to defaults in JSONUtils or allow us to set the defaults.

Right now, I had to workaround it using IL generation:
var sfAsm = typeof(Snowflake.Data.Client.SnowflakeDbCommand).Assembly;
Type sfJsonUtilsTpe = sfAsm.GetType("Snowflake.Data.Core.JsonUtils");
var method = new DynamicMethod(
    name: "SetSomethingElseField",
    returnType: null,
    parameterTypes: new[] { typeof(JsonSerializerSettings), typeof(JsonSerializerSettings) },
    restrictedSkipVisibility: true
);
var gen = method.GetILGenerator();
gen.Emit(OpCodes.Ldarg_0);
gen.Emit(OpCodes.Ldarg_1);
gen.Emit(OpCodes.Stfld, sfJsonUtilsTpe.GetField("JsonSettings"));
gen.Emit(OpCodes.Ret);

var fieldSetter = (Action<JsonSerializerSettings, JsonSerializerSettings>)method.CreateDelegate(typeof(Action<JsonSerializerSettings, JsonSerializerSettings>));

fieldSetter(null, new JsonSerializerSettings()
{
    ContractResolver = (IContractResolver)new DefaultContractResolver()
    {
        NamingStrategy = (NamingStrategy)new DefaultNamingStrategy()
    },
    TypeNameHandling = TypeNameHandling.None
});

Hope it helps,
Daniel

From: David Szmolka ***@***.***>
Date: Wednesday, 14 June 2023 at 17:52
To: snowflakedb/snowflake-connector-net ***@***.***>
Cc: Daniel Taiber ***@***.***>, Author ***@***.***>
Subject: Re: [snowflakedb/snowflake-connector-net] SQL compilation error: Unsupported data type 'java.util.LinkedHashMap' (Issue #675)

sounds great ! just for the sake of people who might hit the same in the future, if you wish, you could comment what the solution for you was. might help others too.

but, since the issue is resolved for you, i'm marking this as closed (you can still comment on a closed case :) )

**Comment by sfc-gh-dszmolka** [comment] 2023-06-15 06:53
now, that's indeed something which needs a second pair of eyes ! thanks for letting us know. reopened the issue.

**Comment by sfc-gh-igarish** [comment] 2023-06-22 23:39
@sfc-gh-knozderko  cannot reproduce the issue, I need more info from the reporter.
What I would ask about:

If you create a new session with a connection string, you can specify "useProxy=true" or "useProxy=false" and it works as expected. The default value for useProxy is false.

What are the exact steps to reproduce the issue?
How exactly do you create and configure HttpUtil object?
Do you create SFSession object by passing in the connection string useProxy parameter?

**Comment by danieltaiber** [comment] 2023-07-11 08:23
Hi,
In my case it was something to do with a specific table, but rather with NewtonsoftJson default converters.
We were setting a default converter on application start for Dictionary parsing.

Our converter was writing a different representation of a dictionary than the default one.
In turn, it was causing SNF request to be parsed wrong and fail on the database side.



Daniel Taiber
VP R&D
[Image]

T +972 (3) 9233766<tel:+97239233766>
M +972 (54) 5700999<tel:+972545700999>
www.insfocus.com<http://www.insfocus.com/>




From: David Szmolka ***@***.***>
Date: Monday, 10 July 2023 at 18:38
To: snowflakedb/snowflake-connector-net ***@***.***>
Cc: Daniel Taiber ***@***.***>, Author ***@***.***>
Subject: Re: [snowflakedb/snowflake-connector-net] SQL compilation error: Unsupported data type 'java.util.LinkedHashMap' (Issue #675)

so based on the original issue submission, we're trying to reproduce the issue. The table setup is

create or replace table testPutArrayBind(cola REAL, colb TEXT, colc NUMBER(38,0))

but the tests come out successful and issue doesn't reproduces on driver version 2.0.24. So I believe we still need the input I asked for earlier, quoting for convenience:

can you please provide a minimal viable reproduction snippet, which when run, displays the behaviour you raised the issue for ?

also if your situation requires Snowflake-side preparation (e.g. setup a table) or has other, data-specific or runtime-specific aspects, please share that as well.

could you please provide this input to troubleshoot further? also if you're using a specific driver version where you see the issue, that might also be important. thank you in advance !

**Comment by danieltaiber** [comment] 2023-07-18 08:55
Thank you


Daniel Taiber
VP R&D
[Image]

T +972 (3) 9233766<tel:+97239233766>
M +972 (54) 5700999<tel:+972545700999>
www.insfocus.com<http://www.insfocus.com/>




From: David Szmolka ***@***.***>
Date: Tuesday, 18 July 2023 at 11:24
To: snowflakedb/snowflake-connector-net ***@***.***>
Cc: Daniel Taiber ***@***.***>, Author ***@***.***>
Subject: Re: [snowflakedb/snowflake-connector-net] SQL compilation error: Unsupported data type 'java.util.LinkedHashMap' (Issue #675)

#702<https://github.com/snowflakedb/snowflake-connector-net/pull/702>

**Comment by sfc-gh-dszmolka** [comment] 2023-07-21 08:08
fix is merged and will be part of the next upcoming release, expected towards end of this month

**Comment by sfc-gh-dszmolka** [comment] 2023-07-27 19:02
PR is released as part of the latest Snowflake .NET driver version 2.1.0. Closing this issue.

**Closed by sfc-gh-dszmolka** 2023-07-27 19:02 UTC
Labels: bug, Fixed - Awaiting Release
