### ISSUE TITLE
1M rows OK with 1.0.6, but not with later versions

### ISSUE THREAD

**Issue by realrael2** [snowflakedb/snowflake-connector-net#159] opened 2019-08-13 07:42 UTC
### Issue description
I have a simple one-table query that returns 60 columns x 1M rows. This works fine up to 1.0.6. Starting with 1.0.7, it stops returning data which I believe is related to #153. I tried the most recent 1.0.13, and it doesn't "hang" anymore (kudos!), but it throws out either an out-of-memory exception, or "The request was aborted".

Experiments done:

- **1.0.6: 1M rows - OK!**
- 1.0.7: 1M rows - Does not return, must be related to #153.
- 1.0.13: 1M rows (starting from 700k rows) - Error out-of-memory or request aborted.
- **1.0.13: 600k rows or less - OK!**

While 1.0.13 made the handling more graceful, it seems after 1.0.6, it's seems less able to handle the data volume.

Appreciate anyone looking into this.

### Example code
```cs
IDbConnection conn = new SnowflakeDbConnection();

conn.ConnectionString = "***";

String sql;
sql = @"select * from some.table limit 1000000;";

conn.Open();

IDbCommand cmd = conn.CreateCommand();
cmd.CommandText = sql;

IDataReader reader = cmd.ExecuteReader();

DataTable dt = new DataTable();

dt.Load(reader);

dataGridView1.AutoGenerateColumns = true;
dataGridView1.DataSource = dt;
dataGridView1.Refresh();

conn.Close();
```

### Error log
```
Please see errors below.
```
![image](https://user-images.githubusercontent.com/52952870/62922056-0c1a8f00-bddd-11e9-8ac3-c3230633ff1c.png)
![image](https://user-images.githubusercontent.com/52952870/62922103-29e7f400-bddd-11e9-84d6-8b14df61675e.png)

### Configuration
*Driver version:* 1.0.7 & 1.0.13

*Dotnet framework and version:* .NET 4.6.1

*Server version:* 3.36.3

*Client OS:* Windows 10

**Comment by stegus64** [comment] 2019-08-13 10:52
I can confirm this problem.

When reading from a very large table, even code like this generates OutOfMemoryException:

```
            IDataReader reader = cmd.ExecuteReader();
            int rowcount = 0;
            while (reader.Read())
            {
                rowcount++;
            }
```

I have also tried using 

`            Snowflake.Data.Configuration.SFConfiguration.Instance().ChunkDownloaderVersion = 1;
`

And I still get the OutOfMemoryException

There seems to be a memory leak somewhere that affects both ChunkDownloaders.

**Comment by stegus64** [comment] 2019-08-13 22:30
Some more information: 

The OutOfMemoryException happens in a 32-bit process. It is easy to reproduce using a Winforms program that just reads from a very large table using a datareader.

When using SFBlockingChunkDownloaderV3 it seems that the problem is not really a memory leak, but each SFReusable chunk uses over 700MB memory when downloading chunks of maximum size.

4 active chunks means almost 3GB memory which might not fit in a 32-bit process (due to memory fragmentation for example)

I think you need to reduce the number of active SFReusableChunk objects. You should probably never use more than two.

**Comment by realrael2** [comment] 2019-08-15 08:54
Thanks so much for digging deeper, @stegus64!

**Comment by stegus64** [comment] 2019-08-15 11:08
I have created a pr #161 to fix this issue

**Comment by ChTimTsubasa** [comment] 2019-08-20 18:35
@realrael2 Before the fix is in, you can set the session parameter [CLIENT_PREFETCH_THREADS](https://docs.snowflake.net/manuals/sql-reference/parameters.html#client-prefetch-threads) to limit the number of threads.

**Comment by realrael2** [comment] 2019-08-22 09:08
Hmmm, it seems to have not helped. All tests cases against 1M rows.

**1.0.6: CLIENT_PREFETCH_THREADS = 4 - OK!**
1.0.6: CLIENT_PREFETCH_THREADS = 2 - The request was aborted: The request was canceled.
1.0.13: CLIENT_PREFETCH_THREADS = 4 - Exception of type 'System.OutOfMemoryException' was thrown.
1.0.13: CLIENT_PREFETCH_THREADS = 2 - Exception of type 'System.OutOfMemoryException' was thrown.

**Comment by stegus64** [comment] 2019-08-22 14:25
Please note that if you are using code like this:

```
IDataReader reader = cmd.ExecuteReader();

DataTable dt = new DataTable();

dt.Load(reader);

```

you are storing the complete result set in memory.

If you are reading a million rows all of that data must fit in your 32-bit process in addition to the overhead controlled by CLIENT_PREFETCH_THREADS.

Do you really need to store 1 million rows in a DataTable?

If you do, I would suggest using a 64-bit process instead.

**Comment by realrael2** [comment] 2019-08-22 16:57
If the next release is gonna resolve this, I can wait.

I'm not keen on workarounds or other alternatives for now because there's a 1.0.6 that can handle the required data volume without hitch.

**Comment by ChTimTsubasa** [comment] 2019-08-22 21:10
The next release 1.0.14 is not likely to include the #161 fix since it hasn't passed one of the CI environment and I am still looking at it.

**Closed** 2019-09-16 21:46 UTC
Labels: jira

**Comment by realrael2** [comment] 2019-09-17 05:14
@stegus64, Curious, were you able to test 1.0.15 against your own test case?

For my original test case, I'm still getting out of memory...
