### ISSUE TITLE
Exhausting the connection pool seems to Crash the application bypassing exception handlers

### ISSUE THREAD

**Issue by garethrepton** [snowflakedb/snowflake-connector-net#548] opened 2022-10-31 18:12 UTC
### Issue description
Exhausting the connection pool seems to Crash the application bypassing exception handlers. I don't have any specific code to reproduce right now, but it appears if I open enough connections eventually the application just ends, without hitting any of my exception handlers.

### Example code
N/A

### Error log
N/A

### Configuration
2.0.13 - 2.0.17

Dotnet 6

**Comment by sfc-gh-igarish** [comment] 2023-06-01 01:44
Thanks for reporting issue. We will look into it.

**Comment by sfc-gh-dszmolka** [comment] 2023-06-12 10:59
Thank you for your patience on this matter. We can indeed say the connection pooling in older version like 2.0.17 is not stable and we've had many fixes since then. Such as: 
snowflakedb/snowflake-connector-net#636
snowflakedb/snowflake-connector-net#642
snowflakedb/snowflake-connector-net#656
snowflakedb/snowflake-connector-net#666

The original issue here more sounds like something we fixed in snowflakedb/snowflake-connector-net#642 but without a runnable reproduction code and the driver logs, it's hard to confirm.

With the recent fixes above especially the test cases added here:
https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data.Tests/SFConnectionIT.cs#L1485
https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data.Tests/SFConnectionPoolT.cs#L34
https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data.Tests/SFConnectionPoolT.cs#L500
Which create 100~1000 connections in around 2 minutes, we have much better test coverage on concurrent connections now.

As of next step, we can recommend you to try the latest driver version which is currently 2.0.24 but if you can wait 1-2 weeks more, the new version 2.0.25 will be coming and see if the issue has been fixed already.

Since we think it is since 2.0.17, I'm now closing this issue as closed but please do comment if you see the issue happening even with the latest driver. If so, we would require as a minimum:
* runnable reproduction code, which when ran, exhibits the issue described in the initial issue description
* (optional) driver logs made during the reproduction

**Closed by sfc-gh-dszmolka** 2023-06-12 10:59 UTC
Labels: bug, In Progress
