### ISSUE TITLE
Can't open connection in .Net Core project

### ISSUE THREAD

**Issue by borysl** [snowflakedb/snowflake-connector-net#160] opened 2019-08-14 08:18 UTC
### Issue description
Looks the same as in https://github.com/snowflakedb/snowflake-connector-net/issues/11
Take the example from the README and try to run
Receive task has been cancelled on connection opened;
### Example code
```cs
        static void Main(string[] args)
        {
            using (IDbConnection conn = new SnowflakeDbConnection())
            {
                var connectionString = "...";
                conn.ConnectionString = connectionString;
                conn.Open(); // Fails here

                IDbCommand cmd = conn.CreateCommand();
                cmd.CommandText = "select * from META_DATA.LOG_MESSAGES order by LOG_TS desc limit 10";
                IDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    Console.WriteLine(reader.GetString(0));
                }

                conn.Close();
            }
        }
```

### Error log
```
   at Snowflake.Data.Client.SnowflakeDbConnection.Open()
   at SFClient.Program.Main(String[] args) in C:\fenix-data\SFClient\Program.cs:line 15
```
There is an example in READMD.md file showing you how to enable logging.

### Configuration
*Driver version:* 1.0.13
*Dotnet framework and version:* .Net Core 2.2.300
*Server version:* 3.36.3
*Client OS:* Windows 10

**Comment by borysl** [comment] 2019-08-14 08:19
![2019-08-14_11h17_41](https://user-images.githubusercontent.com/1067756/63005493-5b1bff00-be85-11e9-8338-2e814c747bff.png)

How it looks in my environment

**Comment by urbrioche** [comment] 2019-08-28 13:11
I encounter the similar connection issue in .net 4.7.
I try to log the error message.
![image](https://user-images.githubusercontent.com/13186486/63858089-7899ae80-c9d7-11e9-96d3-81223dfceee5.png)

I comment "ServicePointManager.CheckCertificateRevocationList = true" in HttpUtil.cs.
And then I can open the connection, not sure if this code works for you.

`        
static private void initHttpClient()
        {
            // enforce tls v1.2
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            ServicePointManager.UseNagleAlgorithm = false;
            // comment the code
            //ServicePointManager.CheckCertificateRevocationList = true;

            HttpUtil.httpClient = new HttpClient(new RetryHandler(new HttpClientHandler(){
                AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate
            }));
        }
`

**Comment by urbrioche** [comment] 2019-09-06 13:38
I think it should be related to OCSP.
.NET connector should also implement [fail-open/fail-close](https://docs.snowflake.net/manuals/release-notes/2019-05.html#snowflake-clients-now-use-fail-open-for-ocsp-revocation-checking) configuration similar to other connector.

initHttpClient() in [HttpUtil.cs](https://github.com/snowflakedb/snowflake-connector-net/blob/master/Snowflake.Data/Core/HttpUtil.cs), HttpClientHandler initialization can change as bellow 

var handler = new HttpClientHandler();
handler.ClientCertificateOptions = ClientCertificateOption.Manual;
// if allow fail-open add the following code
handler.ServerCertificateCustomValidationCallback = delegate { return true; };
var client = new HttpClient(handler);

**Comment by Janatbek** [comment] 2019-10-04 18:41
![image](https://user-images.githubusercontent.com/16279325/66231589-17cf5700-e6a4-11e9-9607-efc08b66f543.png)

I believe it's because you are missing a semicolon at the end of `schema=META_DATA"`  try adding `schema=META_DATA;"`
and check if your connection string separates values with semicolon

**Comment by KoditkarVedant** [comment] 2019-11-07 16:24
Is there any solution to this issue?

**Comment by yannickvidal** [comment] 2020-02-13 15:05
I just had the same issue, triple check your connection string. Mine was missing `HOST=MY_ACCOUNT_NAME.eu-central-1.snowflakecomputing.com`. The default region is `us-west` so `conn.Open();`was hanging forever

If it helps anyone, I am using Snowflake.Data v1.1.0 and Microsoft.AspNetCore.All v2.1.9

**Comment by NJarZe** [comment] 2020-07-13 19:56
I was having the same problem, and I figured it was my connection string. 
What wasn't clear was that you have to type the account AND retype it in the host. If your account is "myComp" and hosted in west Europe Azure (for example) then your connection string would be something like
account=myComp;host=myComp.west-europe.azure.snowflakecomputing.com;user=myUser;password=myPassword;db=myDB;warehouse=MYWH;role=sec_role;"

**Comment by JorgeArellano** [comment] 2020-09-15 18:07
We were facing the same error when running the code in a docker container in Linux, we added the ServerCertificateCustomValidationCallback for the HttpClientHandler being used during client initialization inside the library and logged the validation errors.

We were getting a **RemoteCertificateNameMismatch** policy status error but everything else was good. After looking at this issue https://github.com/dotnet/runtime/issues/35880 we confirmed that it was the case for us, our connection string was like MyCompany_Dev.us-east-1.snoflakecomputing,com, snowflake supports dashes instead of underscores automatically, so, when we change our connection string to MyCompany-Dev.us-east-1.snowflakecomputing.com we were able to connect with no issues in Linux.

**Comment by sfc-gh-jtang** [comment] 2023-05-25 17:40
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link Snowflake Community is the fastest way to get a response.

**Closed by sfc-gh-jtang** 2023-05-25 17:40 UTC
Labels: bug
