### ISSUE TITLE
SNOW-1653627: Support For Entity Framework Core

### ISSUE THREAD

**Issue by harrypooni-118** [snowflakedb/snowflake-connector-net#1021] opened 2024-09-06 10:31 UTC
## What is the current behavior?
No support for native EF Core with Snowflake

## What is the desired behavior?
Support for EF Core so integration can be more seamless without the need of lots of custom code. 

## How would this improve `snowflake-connector-net`?
Wider adoption by .net developers of Snowflake 

## References, Other Background
Many Database technologies have adopted EF Core to unify implementation for .net devs. 

## What is your Snowflake account identifier, if any?
No idea, i am new.

**Comment by sfc-gh-dszmolka** [comment] 2024-09-09 04:54
hi - thank you for your interest in this feature ! Effort is tracked on https://github.com/snowflakedb/snowflake-connector-net/issues/426, and if you wish to participate in the currently ongoing private preview, please reach out to your Snowflake account team who can help you get onboarded.

Closing this for now as it is a duplicate of an existing ticket.

**Closed by sfc-gh-dszmolka** 2024-09-09 04:54 UTC
Labels: feature, status-triage_done
