### ISSUE TITLE
SNOW-1769743: Improve the external browser authentication when pooling is enabled

### ISSUE THREAD

**Issue by nadirhadji** [snowflakedb/snowflake-connector-net#1050] opened 2024-10-28 16:42 UTC
## What is the current behavior?

Currently, when using external browser authentication while running an app that uses connection pooling, many browser windows open, making it difficult to do anything else until the pool is in an idle state.

The context of the project I’m working on requires this method to connect to Snowflake.

## What is the desired behavior?

It would be preferable to have the external browser authentication run in the background (or silently).

## How would this improve `snowflake-connector-net`?

This would improve local development and testing for developers like me who need to use external browser authentication and connection pooling together. If you have any advice or an approach to recommend, it would be greatly appreciated. 😊

**Comment by sfc-gh-dszmolka** [comment] 2024-10-28 18:44
hello - unfortunately the driver does not support SSO token caching at this moment, contrary to other Snowflake drivers. 
there's already work ongoing on implementing the feature (without timeline available), you can follow the progress on https://github.com/snowflakedb/snowflake-connector-net/issues/380

In the meantime, you can consider using the ODBC driver if that's an option for you; it already has connection token caching (both for SSO and MFA tokens).

I'm closing this issue because it's a duplicate of an ongoing work.

**Closed by sfc-gh-dszmolka** 2024-10-28 18:44 UTC
Labels: duplicate, feature, status-triage_done
