### ISSUE TITLE
SNOW-1346563: Authorization issue (Method not found: Void Microsoft.IdentityModel.Tokens.InternalValidators.ValidateLifetimeAndIssuerAfterSignatureNotValidatedSaml)

### ISSUE THREAD

**Issue by raffi1965** [snowflakedb/snowflake-connector-net#932] opened 2024-04-25 16:47 UTC
1.Used: core 6.0
2. OS: windows 10

I add Snowflaka.Data v3.1.0 to project
Run project and try to authenticate to Azure via B2B
It throws exception
MissingMethodException: Method not found: 'Void Microsoft.IdentityModel.Tokens.InternalValidators.ValidateLifetimeAndIssuerAfterSignatureNotValidatedSaml(Microsoft.IdentityModel.Tokens.SecurityToken, System.Nullable`1<System.DateTime>, System.Nullable`1<System.DateTime>, System.String, Microsoft.IdentityModel.Tokens.TokenValidationParameters, System.Text.StringBuilder)'.

**Comment by sfc-gh-dszmolka** [comment] 2024-04-26 07:28
hi and thanks for raising this issue. The stack snippet you included does not seem to come from Snowflake so I'm wondering how is this issue originating or caused by the Snowflake .NET driver.

Can you please provide a runnable reproduction with environment setup so we could reproduce the same issue ? 

In the meantime I did a quick search and although it's a different type of token, https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1792 looks very similar to the issue you're seeing.
Can you try the workarounds discussed in the above issue, for example:
* downgrading to 6.10.10 / 6.14.1
* making sure all the other related `Microsoft.IdentityModel.*` packages ar at the same version as 1Microsoft.IdentityModel.Tokens`
* adding `Microsoft.IdentityModel.Protocols.OpenIdConnect` to your project
* and the rest of the workarounds discussed in the issue

If you think this issue is coming from Snowflake, happy to investigate further but I would kindly require you to provide a reproduction and details . Thank you in advance !

**Comment by raffi1965** [comment] 2024-04-26 07:52
Reproduction step:
1. create .net core web api project (v6.0)
2. register application instance in Azure AD
3. apply authentication for the registered instance
![image](https://github.com/snowflakedb/snowflake-connector-net/assets/37660354/89ab1ac8-2027-4d76-8222-d9901eb8c5f2)

4. run application from VS - it should be successfull
5. add Snowflaka.Data nuget to the project
6. run project - it should fail with the exception

**Comment by sfc-gh-dszmolka** [comment] 2024-04-26 10:32
Thank you! Checked the repro you sent but apparently it needs considerable setup and an Azure subscription too, so will not be trivial to set up and might take some time. Thus in parallel, checked what else we can do here.

So dependency `Microsoft.IdentityModel.Tokens` is a transitive dependency for `Snowflake.Data`, and seems to come from direct dependency `System.IdentityModel.Tokens.Jwt                            6.34.0` . 

That does not mean the issue is coming from Snowflake, though. 

To confirm you're hitting the issue (or similar issue) which I linked above, could you please, in your repro
1. instead of `Snowflake.Data` 3.1.0, add `Snowflake.Data` 2.1.5 - checked and this was the last version which seems to still have used [<6.15 version](https://github.com/snowflakedb/snowflake-connector-net/blob/v2.1.5/Snowflake.Data/Snowflake.Data.csproj#L30) of `Microsoft.IdentityModel.Tokens`
2. retest

If it works now, it is likely due to the issue related to the linked issue, and hopefully the workarounds listed on the linked Microsoft issue help you tackling the problem in the newer version of transitive dependency `Microsoft.IdentityModel.Tokens`  too.

**Comment by sfc-gh-dszmolka** [comment] 2024-04-26 14:24
thank you for testing - can you please try the workarounds in the linked Microsoft issue ? The problem does not come from the Snowflake library based on the information I got so far. Another search in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet points to a possible solution which is already mentioned in the workarounds in the linked issue (all `Microsoft.IdentityModel` installed need to be on the same version)

If it doesn't work either (installing the same `Microsoft.IdentityModel` version for each installed `Microsoft.IdentityModel.*` module), and you tried all of the workarounds mentioned in the linked Microsoft issue, I suggest raising this in the repo mentioned in this comment.

**Comment by raffi1965** [comment] 2024-04-29 19:40
I didn't quite get you: **Snowflake.Data** doesnt have dependency on **Microsoft.Identity.Model**
It depends on **System.IdentityModel.Tokens.Jwt**

![image](https://github.com/snowflakedb/snowflake-connector-net/assets/37660354/6003b290-1f18-4ec9-97be-8abc97907cef)

**Comment by sfc-gh-dszmolka** [comment] 2024-04-30 04:44
indeed Snowflake.Data does not have a _direct_ dependency on Microsoft.Identity.Model, that's why I [mentioned](https://github.com/snowflakedb/snowflake-connector-net/issues/932#issuecomment-2079123946) that `Microsoft.Identity.Model` is a _transitive_ dependency.

Look at `obj/project.assets.json' in your project , it's the simplest way to see the dependencies (there are others).
```
      "Snowflake.Data/3.1.0": {
        "type": "package",
        "dependencies": {
          "AWSSDK.S3": "3.7.0.4",
          "Apache.Arrow": "14.0.2",
          "Azure.Storage.Blobs": "12.13.0",
          "Azure.Storage.Common": "12.12.0",
          "BouncyCastle.Cryptography": "2.2.1",
          "Google.Cloud.Storage.V1": "4.6.0",
          "Mono.Unix": "7.1.0-final.1.21458.1",
          "Newtonsoft.Json": "13.0.3",
>>>       "System.IdentityModel.Tokens.Jwt": "6.34.0",
          "System.Text.RegularExpressions": "4.3.1",
          "log4net": "2.0.12"
        },
```

dependency of Snowflake.Data. However, dependencies can have their own dependencies to work correctly and those have to be installed too. So for `System.IdentityModel.Tokens.Jwt`:
```
      "System.IdentityModel.Tokens.Jwt/6.34.0": {
        "type": "package",
        "dependencies": {
          "Microsoft.IdentityModel.JsonWebTokens": "6.34.0",
>>>       "Microsoft.IdentityModel.Tokens": "6.34.0"
```

and so on. 

I'm now closing this issue as it does not seem like something originating from Snowflake; rather `Microsoft.IdentityModel.Tokens` and/or other `Microsoft.IdentityModel.*` libraries as explained above.

For a solution, please try the workarounds from the linked issue and if none of them work, please file an Issue directly with the repository mentioned above.

**Closed by sfc-gh-dszmolka** 2024-04-30 04:44 UTC
Labels: question, status-triage_done
