### ISSUE TITLE
SNOW-165183: executing COPY via ExecuteReader doesn't return ResultSet

### ISSUE THREAD

**Issue by jjjain** [snowflakedb/snowflake-connector-net#212] opened 2020-06-05 03:01 UTC
### Issue description
when you execute COPY command on Snowflake UI, you can see all the rows outputted with rows_parsed, rows_loaded for each file.

When you execute this in .Net via ExecuteReader and fill DataTable (DataTable.Fill(reader), you don't get back the output.

When you ExecuteNonQuery, you get back no of rows inserted for last file.

### Example code
cmd.CommandText = "COPY INTO...";
int rowsCopied = cmd.ExecuteNonQuery()
// returns no of rows from last file.

I want to get total count.

### Error log

There is an example in READMD.md file showing you how to enable logging.

### Configuration
*Driver version:*1.1.2

*Dotnet framework and version:* E.g. .net framework 4.5.2 or .net standard 2.0

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10

**Comment by wildgordo** [comment] 2020-07-06 15:33
COPY commands used to return a result set with one row. Looks like the behavior changed sometime after 6:00 PM Pacific on 1 July. I cannot find any support notifications from Snowflake that indicate a change in this behavior.

**Comment by sfc-gh-kterada** [comment] 2021-08-19 21:08
@wildgordo, there have been several releases of the .NET connector GA'd since this was last updated. Are you still able to reproduce the issue reported with the latest GA connector?

**Comment by sfc-gh-igarish** [comment] 2023-03-30 02:31
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of April 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.

**Closed by sfc-gh-igarish** 2023-03-30 02:31 UTC
